CREATE TABLE DOCTOR
(
    ID                INTEGER
        CONSTRAINT HOSPITAL_NN1 NOT NULL,
    NAME              char(100)
        CONSTRAINT DOCTOR_NN2 NOT NULL,
    SURNAME           char(100)
        CONSTRAINT DOCTOR_NN2 NOT NULL,
    POLICLINIC_TYPE   varchar(50)
        CONSTRAINT DOCTOR_NN4 NOT NULL,
    INTERVENTION_TYPE varchar(50)
        CONSTRAINT DOCTOR_NN4 NOT NULL,
    PANTIENT_ID       INTEGER
        CONSTRAINT DOCTOR_NN3 NOT NULL

);
CREATE
    INDEX IDX_DOCTOR_FBI ON DOCTOR (ID);

INSERT INTO DOCTOR (ID, NAME, SURNAME, POLICLINIC_TYPE, PANTIENT_ID, INTERVENTION_TYPE)
VALUES (1, 'Doğan', 'Oruçlu', 'URGENT', 1, 'DRESSING');


COMMIT;