CREATE TABLE OPERATION
(
    ID             INTEGER
        CONSTRAINT OPERATION_NN1 NOT NULL,
    PANTIENT_ID    INTEGER
        CONSTRAINT OPERATION_NN2 NOT NULL,
    CONDOLITION_ID INTEGER
        CONSTRAINT OPERATION_NN3 NOT NULL,
    HOSPITAL_ID    INTEGER
        CONSTRAINT OPERATION_NN4 NOT NULL
);
CREATE
    INDEX IDX_OPERATION_FBI ON OPERATION (ID);

INSERT INTO OPERATION (ID, PANTIENT_ID, CONDOLITION_ID, HOSPITAL_ID)
VALUES (1, 1, 1, 1);
INSERT INTO OPERATION (ID, PANTIENT_ID, CONDOLITION_ID, HOSPITAL_ID)
VALUES (2, 2, 2, 2);

COMMIT;