CREATE TABLE PATIENT
(
    ID      INTEGER
        CONSTRAINT PATIENT_NN1 NOT NULL,
    NAME    varchar(10)
        CONSTRAINT PATIENT_NN2 NOT NULL,
    SURNAME varchar(10)
        CONSTRAINT PATIENT_NN3 NOT NULL,
    GENDER  varchar(7)
        CONSTRAINT PATIENT_NN4 NOT NULL,
    AGE     INTEGER
        CONSTRAINT PATIENT_NN5 NOT NULL,
    SIZE    INTEGER
        CONSTRAINT PATIENT_NN6 NOT NULL,
    KG      INTEGER
        CONSTRAINT PATIENT_NN7 NOT NULL

);
CREATE
    INDEX IDX_PATIENT_FBI ON PANTIENT (ID);

INSERT INTO PANTIENT (ID, NAME, SURNAME, GENDER, AGE, SIZE, KG)
VALUES (1, 'ABUZER', 'WICK', 'MALE', 19, 167, 67);
INSERT INTO PANTIENT (ID, NAME, SURNAME, GENDER, AGE, SIZE, KG)
VALUES (2, 'EMILY', 'JHON', 'WOMAN', 27, 190, 78);
INSERT INTO PANTIENT (ID, NAME, SURNAME, GENDER, AGE, SIZE, KG)
VALUES (3, 'ALPER', 'WICK', 'MALE', 90, 200, 110);


COMMIT;
