CREATE TABLE HOSPITAL
(
    ID          INTEGER
        CONSTRAINT HOSPITAL_NN1 NOT NULL,
    NAME        char(100)
        CONSTRAINT HOSPITAL_NN2 NOT NULL,
    PANTIENT_ID INTEGER
        CONSTRAINT HOSPITAL_NN3 NOT NULL,
    DOCTOR_ID   INTEGER
        CONSTRAINT HOSPITAL_NN4 NOT NULL
);
CREATE
    INDEX IDX_HOSPITAL_FBI ON HOSPITAL (ID);

INSERT INTO HOSPITAL (ID, NAME, DOCTOR_ID, PANTIENT_ID)
VALUES (1, 'ANKARA SEHIR HASTANESİ', 1, 1);
INSERT INTO HOSPITAL (ID, NAME, DOCTOR_ID, PANTIENT_ID)
VALUES (2, 'DENIZLI SEHIR HASTANESİ', 2, 2);
INSERT INTO HOSPITAL (ID, NAME, DOCTOR_ID, PANTIENT_ID)
VALUES (3, 'KONYA SEHIR HASTANESİ', 3, 3);

COMMIT;
