CREATE TABLE CONDILITION
(
    ID               INTEGER
        CONSTRAINT CONDILITION_NN1 NOT NULL,
    INFO             char(400)
        CONSTRAINT CONDILITION_NN2 NOT NULL,
    SERIOUSNESS_TYPE varchar(50)
        CONSTRAINT CONDILITION_NN3 NOT NULL
);
CREATE
    INDEX IDX_CONDILITION_FBI ON CONDILITION (ID);

INSERT INTO CONDILITION (ID, INFO, SERIOUSNESS_TYPE)
VALUES (1, 'Burn', 'RED');

COMMIT;